version: "3.7"

services:
  server:
    container_name: "${PROJECT_NAME}_server"
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    networks:
      - default
      - external-services

networks:
  external-services:
    external: true
