"""Initial migration

Revision ID: 7eae23d40597
Revises: 
Create Date: 2024-11-18 11:41:55.387998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eae23d40597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pollution_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('air_quality_index', sa.Integer(), nullable=True),
    sa.Column('water_quality_index', sa.Integer(), nullable=True),
    sa.Column('ph_level', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pollution_history')
    # ### end Alembic commands ###
